# Generated by Django 5.0 on 2023-12-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_key_code_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(editable=False, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='key_code',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(editable=False, max_length=150, null=True),
        ),
    ]
